name: My CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Checkout on commit in the repository"
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t yapro/apiration-bundle:latest -f ./Dockerfile ./
#      docker build . --file Dockerfile --tag my-image-name:latest
    - name: run command in docker
      run: docker run --rm -v $(pwd):/app -w /app yapro/apiration-bundle:latest composer install --optimize-autoloader --no-scripts --no-interaction

#    - uses: addnab/docker-run-action@v3
#      with:
#        image: php:7-fpm-buster
#        options: -v ${{ github.workspace }}:/app -e ABC=123
#        run: |
#          composer install --optimize-autoloader --no-scripts --no-interaction
#          vendor/bin/simple-phpunit --testsuite=Unit,Functional

#    - name: My first step
#      uses: docker://php:7-fpm-buster
#      with:
#        entrypoint: /usr/local/bin/php -v
#    - name: run command
#      run: php -v
#      run: composer validate --strict
