name: My CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Checkout on commit in the repository"
      uses: actions/checkout@v2
    - name: My first step
      uses: docker://php:7-fpm-buster
      with:
        entrypoint: php -v
#    - name: run command
#      run: php -v
#      run: composer validate --strict
